# Generated by Django 4.2.15 on 2025-01-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='is_primary',
        ),
    ]
