# Generated by Django 4.2.15 on 2025-01-06 00:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_booking_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomimage",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="amenity",
            name="icon",
            field=models.CharField(
                blank=True, help_text="FontAwesome icon class", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="roomimage",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roomimage",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
